magfest/terraform-aws-magfest

uber_config/events/super/2024/init.yaml
uber_config/events/west/2023/init.yaml

This should let us actually see the registration form.

Set new servers' post-con variable to false

---

uber_config/events/west/2023/init.yaml

More changes to come, but this handles some deadlines that I already know or have taken a good guess on.

Plugging in some variables for 2023!

---

servers.yaml

OK, it shouldn't break now probably!

Update prefix names as well

---

servers.yaml

Let's see if I can migrate one (1) old server from DO

Add West 2021 server

---

uber_config/events/west/2023/init.yaml

Mostly just messing with dates! (Oh also prices)

Application date updates

---

uber_config/events/west/init.yaml

This will enable the new "content rating" dropdown for panel applications.

Add panel ratings for West

---

uber_config/events/stock/2023/init.yaml
uber_config/events/stock/init.yaml

Fixes https://jira.magfest.net/browse/MAGDEV-1230. Fixes https://jira.magfest.net/browse/MAGDEV-883.
More changes may be needed for the volunteer checklist, but it helps if you can actually see those steps first.

Update DH and volunteer checklist steps for Stock 2023

---

uber_config/events/stock/2023/init.yaml
uber_config/events/stock/init.yaml

Fixes part of https://jira.magfest.net/browse/MAGDEV-1196. Fixes https://jira.magfest.net/browse/MAGDEV-1237.

Update MAGStock permanent config

---

uber_config/events/stock/2023/init.yaml
uber_config/events/west/2023/init.yaml

I thought it would repeat links, but apparently you need to relink each item in the description.

Fix merch descriptions for West and Stock

---

uber_config/events/stock/2023/init.yaml
uber_config/events/stock/init.yaml

This should take care of everything in the testing document. I hope.

Possibly final Stock launch fixes

---

servers.yaml
uber_config/events/super/2024/staging/init.yaml

Reg needs the Super staging server up and in at-con mode so they can make training videos!

Add Super staging server

---

uber_config/events/west/2023/init.yaml
uber_config/events/west/init.yaml

Fixes https://jira.magfest.net/browse/MAGDEV-1231. Fixes https://jira.magfest.net/browse/MAGDEV-1232. Fixes https://jira.magfest.net/browse/MAGDEV-1233.

Update volunteer and DH checklists for West

---

uber_config/events/west/2023/init.yaml
uber_config/events/west/init.yaml

I had missed a few updates last week, this should cover what I missed.

Fix West dept head checklist

---

uber_config/events/stock/2023/init.yaml

Temporarily disable emergency procedures step

---

uber_config/events/stock/2023/init.yaml

We have emergency procedures now!

Revert "Temporarily disable emergency procedures step"

---

uber_config/events/stock/2023/staging/init.yaml
uber_config/events/stock/init.yaml

Also sets staging to at-con mode.

Turn off numbered badges for Stock

---

uber_config/events/stock/2023/init.yaml

Turn off Stock 2023 registration

---

uber_config/events/super/2024/init.yaml
uber_config/events/super/init.yaml

Also enables `notify_dealer_applied`, as Danielle wants to still receive application notifications.

Update dealer table prices for Super 2024

---

uber_config/events/super/2024/init.yaml
uber_config/events/super/init.yaml

This is part of https://jira.magfest.net/browse/MAGDEV-1242 -- I'll merge this when the code for it is ready.

Update panels config options

---

modules/ubersystem-ecs/containers.tf
uber_config/events/super/2024/init.yaml
uber_config/events/super/init.yaml

Adds config for updating the reg emails and for using Redis for a global session store on our servers.

Super 2024 prereg launch updates

---

uber_config/events/super/2024/init.yaml

Fixes https://jira.magfest.net/browse/MAGDEV-1257, https://jira.magfest.net/browse/MAGDEV-1258, and https://jira.magfest.net/browse/MAGDEV-1260.

Update Super 2024 dept head checklist

---

servers.yaml

@bitbyt3r Is this enough web servers? I think last time you said 24 was overkill?

Scaling up for at-con

---

uber_config/events/super/2025/init.yaml

To be merged when we sell out (take two)

Stay sold out

---

cloudfront.tf

Reverts magfest/terraform-aws-magfest#68

Revert "Attempt to fix each.value errors"
